### ISSUE TITLE
Running specs fails with "uninitialized constant Shoulda::Matchers::Error (NameError)"

### ISSUE THREAD

**Issue by naiyt** [mavenlink/mavenlink_gem#16]
If I install a fresh copy of mavelink_gem on Ruby 1.9.3 or 2.1.5 and try to run the specs, it fails with:

```
~/.rvm/gems/ruby-2.1.5/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/errors.rb:8:in `<module:ActiveModel>': uninitialized constant Shoulda::Matchers::Error (NameError)
```

It seems the versions of rspec and shoulda-matchers it bundles in now are causing issues. I'm not sure whether it's better to lock in the dependencies to versions that worked previously, or update the specs to work with the newest versions of things.

**Comment by cantino** [comment]
Probably update to newest versions and fix specs.

**Comment by cantino** [comment]
I think this was built on an older version of RSpec.  @einzige, do you recall what version of RSpec and shoulda-matchers this was using?  I want to lock it in `mavenlink.gemspec`.

**Comment by einzige** [comment]
I do apologize, https://github.com/mavenlink/mavenlink_gem/pull/18

**Comment by cantino** [comment]
Thanks for the quick fix!
